#!/usr/bin/env python3
"""Generate docs/data/atlas_data.json from the battery results.

Single source of truth: pipeline/real_run_w5_w11/results_summary.json.
Every number rendered on the atlas site comes from the JSON this script
emits. The script asserts the audit-verified constants and exits non-zero
if anything disagrees, so the site and the results can never silently
diverge.

Usage: python3 docs/build_data.py
"""

import json
import os
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

# Results live in the repo under pipeline/real_run_w5_w11/. Fall back to the
# original analysis location if docs/ is used standalone.
CANDIDATES = [
    os.path.join(REPO, "pipeline", "real_run_w5_w11", "results_summary.json"),
    os.path.expanduser("~/workspace/your_files/fly-connectome-paper-outline"
                       "/pipeline/real_run_w5_w11/results_summary.json"),
]

# ---- Audit-verified constants (pipeline/AUDIT_REPORT.md, 2026-09-13) ----
NEURON_RECORDS = 176422        # :Neuron rows in neuPrint male-cns:v1.0
PAPER_ANNOTATED = 166700       # annotated neurons (paper headline count)
UNANNOTATED = 9722             # records without classification annotation
W5_NODES = 173023              # distinct endpoints of weight>=5 edges
W11_ISOLATES = 6149            # w11 graph vertices with no weight>=11 edge
W11_EFFECTIVE = 166874         # 173023 - 6149
W5_EDGES = 6287749             # directed edges, weight>=5, 40 self-loops removed
W11_EDGES = 2446815            # directed edges, weight>=11, 11 self-loops removed
W5_SELF_LOOPS = 40
W11_SELF_LOOPS = 11
W5_MINCUT_VALUE = 4321207
W5_MINCUT_EDGES = 267027
W11_MINCUT_VALUE = 3248164
W11_MINCUT_EDGES = 117267
W5_REACH = 59795264
W11_REACH = 55738955
TOTAL_PAIRS = 60201504         # 26972 in-graph sensory x 2232 in-graph motor
W5_DISJOINT_MEAN = 20.74       # rounded display value; exact 20.7360...
W11_DISJOINT_MEAN = 8.68       # rounded display value; exact 8.6816...

STRATEGY_LABELS = {
    "random": "Random removal",
    "out_degree": "Highest out-degree first",
    "betweenness_approx": "Highest approximate betweenness first",
    "mincut_membership": "Minimum-cut membership first",
    "weight": "Heaviest edges first",
}
ELEMENT_LABELS = {"nodes": "Node removal", "edges": "Edge removal"}


def find_results():
    for p in CANDIDATES:
        if os.path.exists(p):
            return p
    raise SystemExit("results_summary.json not found in: " + ", ".join(CANDIDATES))


def mean(xs):
    xs = list(xs)
    return sum(xs) / len(xs) if xs else None


def check(name, got, want):
    if got != want:
        raise SystemExit(f"VERIFY FAIL: {name}: got {got!r}, want {want!r}")
    print(f"  ok {name} = {got}")


def check_close(name, got, want, tol=1e-9):
    if abs(got - want) > tol:
        raise SystemExit(f"VERIFY FAIL: {name}: got {got!r}, want {want!r}")
    print(f"  ok {name} = {got}")


def main():
    src = find_results()
    print("reading", src)
    with open(src) as f:
        res = json.load(f)

    if res.get("data") != "REAL MaleCNS v1.0 (neuprint.janelia.org), not synthetic":
        raise SystemExit("VERIFY FAIL: unexpected data provenance string")

    out = {"meta": {}, "thresholds": {}, "audit": {}, "fdr": {}, "provenance": {}}

    # ---- meta ----
    out["meta"] = {
        "config_hash": res["config_hash"],
        "elapsed_seconds": res["elapsed_seconds"],
        "source_file": os.path.basename(src),
        "generated_note": ("Generated by docs/build_data.py from "
                           "pipeline/real_run_w5_w11/results_summary.json"),
    }

    # ---- thresholds ----
    for th in ("5", "11"):
        t = res["thresholds"][th]
        g = t["graph_stats"]
        r = t["reachability"]
        dp = t["disjoint_paths"]
        mc = t["mincut"]

        n_nodes = g["n_nodes"]
        n_effective = n_nodes - (W11_ISOLATES if th == "11" else 0)

        # Top cut-set members: most frequent source / target body IDs in the cut.
        src_count = Counter(e[0] for e in mc["cut_edges"])
        tgt_count = Counter(e[1] for e in mc["cut_edges"])
        top_sources = [{"body_id": b, "cut_edges": c}
                       for b, c in src_count.most_common(25)]
        top_targets = [{"body_id": b, "cut_edges": c}
                       for b, c in tgt_count.most_common(25)]

        lesions = {}
        for element, strategies in t["lesions"].items():
            lesions[element] = {}
            for strat, obj in strategies.items():
                curves = {}
                for frac, reps in obj["curves"].items():
                    curves[frac] = {
                        "mean_newly_disconnected": mean(
                            x["newly_disconnected"] for x in reps),
                        "mean_reachable_pairs": mean(
                            x["reachable_pairs"] for x in reps),
                        "n_replicates": len(reps),
                    }
                lesions[element][strat] = {
                    "label": STRATEGY_LABELS[strat],
                    "element_label": ELEMENT_LABELS[element],
                    "baseline_reachable_pairs": obj["baseline_reachable_pairs"],
                    "curves": curves,
                }

        controls = {}
        for strat, fracs in t["controls"].items():
            controls[strat] = {}
            for frac, c in fracs.items():
                perm = c.get("permutation") or {}
                controls[strat][frac] = {
                    "targeted_loss": c.get("targeted_loss"),
                    "control_mean_loss": c.get("control_mean_loss"),
                    "n_controls": c.get("n_controls"),
                    "raw_p_value": perm.get("p_value"),
                    "note": c.get("note"),
                }

        nulls = {}
        for name, n in t["nulls"].items():
            perm = n.get("permutation_vs_observed") or {}
            nulls[name] = {
                "n_replicates": n["n_replicates"],
                "reach_fraction_mean": n["reach_fraction_mean"],
                "reach_fraction_sd": n["reach_fraction_sd"],
                "p_value": perm.get("p_value"),
            }

        out["thresholds"][th] = {
            "graph": {
                "n_nodes": n_nodes,
                "n_nodes_effective": n_effective,
                "n_edges": g["n_edges"],
                "density": g["density"],
                "weak_components": g["weak_components"],
                "largest_weak": g["largest_weak"],
                "strong_components": g["strong_components"],
                "largest_strong": g["largest_strong"],
                "self_loops_removed": W5_SELF_LOOPS if th == "5" else W11_SELF_LOOPS,
                "sensory_in_graph": t["sensory_in_graph"],
                "motor_in_graph": t["motor_in_graph"],
                "sensory_annotated": t["sensory_annotated"],
                "motor_annotated": t["motor_annotated"],
            },
            "reachability": {
                "total_pairs": r["total_pairs"],
                "reachable_pairs": r["reachable_pairs"],
                "fraction_reachable": r["fraction_reachable"],
                "mean_shortest_path": r["mean_shortest_path"],
                "median_shortest_path": r["median_shortest_path"],
                "hop_limited": {k: v for k, v in r["hop_limited_fraction"].items()},
                "method": r["method"],
            },
            "disjoint_paths": {
                "n_pairs_sampled": dp["n_pairs_sampled"],
                "n_pairs_reachable": dp["n_pairs_reachable"],
                "mean": dp["mean_disjoint_paths"],
                "min": dp["min_disjoint_paths"],
                "max": dp["max_disjoint_paths"],
            },
            "mincut": {
                "value": mc["value"],
                "n_cut_edges": mc["n_cut_edges"],
                "top_sources": top_sources,
                "top_targets": top_targets,
                "sample_edges": [list(e) for e in mc["cut_edges"][:100]],
            },
            "lesions": lesions,
            "controls": controls,
            "nulls": nulls,
        }

    # ---- FDR ----
    fdr = res["fdr"]
    out["fdr"] = {
        "n_tests": fdr["n_tests"],
        "n_rejected": fdr["n_rejected"],
        "alpha": 0.05,
        "min_raw_p": min(fdr["p_values"]),
        "min_adjusted_p": min(fdr["p_adjusted"]),
        "labels": fdr["labels"],
    }

    # ---- audit reconciliation ----
    out["audit"] = {
        "neuron_records_downloaded": NEURON_RECORDS,
        "paper_annotated_neurons": PAPER_ANNOTATED,
        "unannotated_records": UNANNOTATED,
        "w5_graph_nodes": W5_NODES,
        "w11_isolated_vertices": W11_ISOLATES,
        "w11_effective_nodes": W11_EFFECTIVE,
        "node_note": ("176,422 neuron records downloaded; the paper's 166,700 "
                      "counts annotated neurons only (9,722 unannotated "
                      "excluded). Battery graphs hold 173,023 nodes: the "
                      "distinct endpoints of weight>=5 edges. The w11 graph "
                      "contains 6,149 isolated vertices with no weight>=11 "
                      "edge, so its effective node count is 166,874."),
    }

    # ---- provenance ----
    out["provenance"] = {
        "dataset": "MaleCNS v1.0",
        "source": "neuprint.janelia.org",
        "paper": "Berg et al., Cell 189(18), 2026",
        "doi": "10.1016/j.cell.2026.08.015",
        "license": "CC BY",
    }

    # ---- verification against audit facts ----
    print("verifying audit constants:")
    t5, t11 = out["thresholds"]["5"], out["thresholds"]["11"]
    check("w5 nodes", t5["graph"]["n_nodes"], W5_NODES)
    check("w11 nodes", t11["graph"]["n_nodes"], W5_NODES)
    check("w11 effective nodes", t11["graph"]["n_nodes_effective"], W11_EFFECTIVE)
    check("w5 edges", t5["graph"]["n_edges"], W5_EDGES)
    check("w11 edges", t11["graph"]["n_edges"], W11_EDGES)
    check("w5 mincut value", t5["mincut"]["value"], float(W5_MINCUT_VALUE))
    check("w5 mincut n edges", t5["mincut"]["n_cut_edges"], W5_MINCUT_EDGES)
    check("w11 mincut value", t11["mincut"]["value"], float(W11_MINCUT_VALUE))
    check("w11 mincut n edges", t11["mincut"]["n_cut_edges"], W11_MINCUT_EDGES)
    check("w5 reachable pairs", t5["reachability"]["reachable_pairs"], W5_REACH)
    check("w11 reachable pairs", t11["reachability"]["reachable_pairs"], W11_REACH)
    check("total pairs", t5["reachability"]["total_pairs"], TOTAL_PAIRS)
    check_close("w5 reach fraction", t5["reachability"]["fraction_reachable"],
                W5_REACH / TOTAL_PAIRS)
    check_close("w11 reach fraction", t11["reachability"]["fraction_reachable"],
                W11_REACH / TOTAL_PAIRS)
    check("fdr n_tests", out["fdr"]["n_tests"], 24)
    check("fdr n_rejected", out["fdr"]["n_rejected"], 0)
    if round(t5["disjoint_paths"]["mean"], 2) != W5_DISJOINT_MEAN:
        raise SystemExit("VERIFY FAIL: w5 disjoint mean")
    print("  ok w5 disjoint mean rounds to", W5_DISJOINT_MEAN)
    if round(t11["disjoint_paths"]["mean"], 2) != W11_DISJOINT_MEAN:
        raise SystemExit("VERIFY FAIL: w11 disjoint mean")
    print("  ok w11 disjoint mean rounds to", W11_DISJOINT_MEAN)
    # cut set internal consistency
    for th in ("5", "11"):
        mc = out["thresholds"][th]["mincut"]
        if len(mc["sample_edges"]) != 100:
            raise SystemExit(f"VERIFY FAIL: t{th} cut edge sample size")
    print("  ok cut edge samples present for both thresholds")

    data_dir = os.path.join(HERE, "data")
    os.makedirs(data_dir, exist_ok=True)
    dest = os.path.join(data_dir, "atlas_data.json")
    with open(dest, "w") as f:
        json.dump(out, f)
    print("wrote", dest, f"({os.path.getsize(dest)} bytes)")
    print("ALL CHECKS PASSED")


if __name__ == "__main__":
    main()
